#!/bin/bash
do_date=`date -d "-1 day" +%F`
db=zfq_test_decent_cloud
hive=/data/program/hive-1.2.1/bin/hive
dir=/test_zfq_decent_cloud
sql="
set hive.exec.dynamic.partition.mode=nonstrict;
load data inpath '$dir/t_bf_area/$do_date' into table $db.t_bf_area partition (dt='$do_date');
load data inpath '$dir/t_bf_bank_deposit_bill_sz/$do_date' into table $db.t_bf_bank_deposit_bill_sz partition (dt='$do_date');
load data inpath '$dir/t_bf_bank_deposit_bill_sz_detail/$do_date' into table $db.t_bf_bank_deposit_bill_sz_detail partition (dt='$do_date');
load data inpath '$dir/t_bf_buy_cus_item/$do_date' into table $db.t_bf_buy_cus_item partition (dt='$do_date');
load data inpath '$dir/t_bf_buy_cus_item_detail/$do_date' into table $db.t_bf_buy_cus_item_detail partition (dt='$do_date');
load data inpath '$dir/t_bf_buy_cus_material/$do_date' into table $db.t_bf_buy_cus_material partition (dt='$do_date');
load data inpath '$dir/t_bf_buyback_material/$do_date' into table $db.t_bf_buyback_material partition (dt='$do_date');
load data inpath '$dir/t_bf_change_outsource/$do_date' into table $db.t_bf_change_outsource partition (dt='$do_date');
load data inpath '$dir/t_bf_cus_credit_receipt/$do_date' into table $db.t_bf_cus_credit_receipt partition (dt='$do_date');
load data inpath '$dir/t_bf_cus_debit_receipt/$do_date' into table $db.t_bf_cus_debit_receipt partition (dt='$do_date');
load data inpath '$dir/t_bf_cust_return_jewelry/$do_date' into table $db.t_bf_cust_return_jewelry partition (dt='$do_date');
load data inpath '$dir/t_bf_cust_return_jewelry_detail/$do_date' into table $db.t_bf_cust_return_jewelry_detail partition (dt='$do_date');
load data inpath '$dir/t_bf_customer_the_bill/$do_date' into table $db.t_bf_customer_the_bill partition (dt='$do_date');
load data inpath '$dir/t_bf_dkhhy_b/$do_date' into table $db.t_bf_dkhhy_b partition (dt='$do_date');
load data inpath '$dir/t_bf_dkhhy_h/$do_date' into table $db.t_bf_dkhhy_h partition (dt='$do_date');
load data inpath '$dir/t_bf_gold_transfer_in/$do_date' into table $db.t_bf_gold_transfer_in partition (dt='$do_date');
load data inpath '$dir/t_bf_gold_transfer_out/$do_date' into table $db.t_bf_gold_transfer_out partition (dt='$do_date');
load data inpath '$dir/t_bf_gold_transfer_out_detail/$do_date' into table $db.t_bf_gold_transfer_out_detail partition (dt='$do_date');
load data inpath '$dir/t_bf_gold_transfer_out_print/$do_date' into table $db.t_bf_gold_transfer_out_print partition (dt='$do_date');
load data inpath '$dir/t_bf_gold_transfer_out_print_detail/$do_date' into table $db.t_bf_gold_transfer_out_print_detail partition (dt='$do_date');
load data inpath '$dir/t_bf_pay_cus_material/$do_date' into table $db.t_bf_pay_cus_material partition (dt='$do_date');
load data inpath '$dir/t_bf_pay_cus_material_detail/$do_date' into table $db.t_bf_pay_cus_material_detail partition (dt='$do_date');
load data inpath '$dir/t_bf_pay_outsource/$do_date' into table $db.t_bf_pay_outsource partition (dt='$do_date');
load data inpath '$dir/t_bf_payment_order/$do_date' into table $db.t_bf_payment_order partition (dt='$do_date');
load data inpath '$dir/t_bf_raw_material/$do_date' into table $db.t_bf_raw_material partition (dt='$do_date');
load data inpath '$dir/t_bf_receive_meterial/$do_date' into table $db.t_bf_receive_meterial partition (dt='$do_date');
load data inpath '$dir/t_bf_receive_meterial_detail/$do_date' into table $db.t_bf_receive_meterial_detail partition (dt='$do_date');
load data inpath '$dir/t_bf_repair/$do_date' into table $db.t_bf_repair partition (dt='$do_date');
load data inpath '$dir/t_bf_retreat/$do_date' into table $db.t_bf_retreat partition (dt='$do_date');
load data inpath '$dir/t_bf_settlement/$do_date' into table $db.t_bf_settlement partition (dt='$do_date');
load data inpath '$dir/t_bf_settlement_adjustment_price/$do_date' into table $db.t_bf_settlement_adjustment_price partition (dt='$do_date');
load data inpath '$dir/t_bf_stock_transfer_bill/$do_date' into table $db.t_bf_stock_transfer_bill partition (dt='$do_date');
load data inpath '$dir/t_bf_szztgzspd/$do_date' into table $db.t_bf_szztgzspd partition (dt='$do_date');
load data inpath '$dir/t_bf_szztgzspd_detail/$do_date' into table $db.t_bf_szztgzspd_detail partition (dt='$do_date');
load data inpath '$dir/t_bf_the_bill/$do_date' into table $db.t_bf_the_bill partition (dt='$do_date');
load data inpath '$dir/t_bf_weighing_form_check/$do_date' into table $db.t_bf_weighing_form_check partition (dt='$do_date');
load data inpath '$dir/t_child_customer/$do_date' into table $db.t_child_customer partition (dt='$do_date');
load data inpath '$dir/t_customer/$do_date' into table $db.t_customer partition (dt='$do_date');
load data inpath '$dir/t_delay_region/$do_date' into table $db.t_delay_region partition (dt='$do_date');
load data inpath '$dir/t_fast_customer/$do_date' into table $db.t_fast_customer partition (dt='$do_date');
load data inpath '$dir/t_fast_package/$do_date' into table $db.t_fast_package partition (dt='$do_date');
load data inpath '$dir/t_fast_package_i/$do_date' into table $db.t_fast_package_i partition (dt='$do_date');
load data inpath '$dir/t_fast_package_i_product/$do_date' into table $db.t_fast_package_i_product partition (dt='$do_date');
load data inpath '$dir/t_finance_customer_relation/$do_date' into table $db.t_finance_customer_relation partition (dt='$do_date');
load data inpath '$dir/t_gf_area_customer/$do_date' into table $db.t_gf_area_customer partition (dt='$do_date');
load data inpath '$dir/t_ka_lllsz/$do_date' into table $db.t_ka_lllsz partition (dt='$do_date');
load data inpath '$dir/t_ka_lscqmxb_b/$do_date' into table $db.t_ka_lscqmxb_b partition (dt='$do_date');
load data inpath '$dir/t_ka_lscqmxb_h/$do_date' into table $db.t_ka_lscqmxb_h partition (dt='$do_date');
load data inpath '$dir/t_ka_splsz/$do_date' into table $db.t_ka_splsz partition (dt='$do_date');
load data inpath '$dir/t_ka_szdzsqdh/$do_date' into table $db.t_ka_szdzsqdh partition (dt='$do_date');
load data inpath '$dir/t_ka_szkhcqlxzz_b/$do_date' into table $db.t_ka_szkhcqlxzz_b partition (dt='$do_date');
load data inpath '$dir/t_ka_szkhcqlxzz_h/$do_date' into table $db.t_ka_szkhcqlxzz_h partition (dt='$do_date');
load data inpath '$dir/t_ka_szkhcqlxzzfb_h/$do_date' into table $db.t_ka_szkhcqlxzzfb_h partition (dt='$do_date');
load data inpath '$dir/t_ka_szkhcqmx_h/$do_date' into table $db.t_ka_szkhcqmx_h partition (dt='$do_date');
load data inpath '$dir/t_ka_szlxjsrq/$do_date' into table $db.t_ka_szlxjsrq partition (dt='$do_date');
load data inpath '$dir/t_ka_yfllsz/$do_date' into table $db.t_ka_yfllsz partition (dt='$do_date');
load data inpath '$dir/t_ka_yflsz/$do_date' into table $db.t_ka_yflsz partition (dt='$do_date');
load data inpath '$dir/t_ka_yslsz/$do_date' into table $db.t_ka_yslsz partition (dt='$do_date');
load data inpath '$dir/t_ka_ysmxz_b/$do_date' into table $db.t_ka_ysmxz_b partition (dt='$do_date');
load data inpath '$dir/t_ka_ysmxz_h/$do_date' into table $db.t_ka_ysmxz_h partition (dt='$do_date');
load data inpath '$dir/t_ka_zrye/$do_date' into table $db.t_ka_zrye partition (dt='$do_date');
load data inpath '$dir/t_ka_ztkcrzz/$do_date' into table $db.t_ka_ztkcrzz partition (dt='$do_date');
load data inpath '$dir/t_move_counter/$do_date' into table $db.t_move_counter partition (dt='$do_date');
load data inpath '$dir/t_purity/$do_date' into table $db.t_purity partition (dt='$do_date');
load data inpath '$dir/t_receive/$do_date' into table $db.t_receive partition (dt='$do_date');
load data inpath '$dir/t_sale_from/$do_date' into table $db.t_sale_from partition (dt='$do_date');
load data inpath '$dir/t_sale_from_account_detail/$do_date' into table $db.t_sale_from_account_detail partition (dt='$do_date');
load data inpath '$dir/t_sale_from_detail/$do_date' into table $db.t_sale_from_detail partition (dt='$do_date');
load data inpath '$dir/t_sales_return/$do_date' into table $db.t_sales_return partition (dt='$do_date');
load data inpath '$dir/t_showroom/$do_date' into table $db.t_showroom partition (dt='$do_date');
load data inpath '$dir/t_showroom_counter/$do_date' into table $db.t_showroom_counter partition (dt='$do_date');
load data inpath '$dir/t_technology_purity/$do_date' into table $db.t_technology_purity partition (dt='$do_date');
 "
$hive -e "$sql"

